[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
  [[redirects]]
from = "/feed.xml"
to = "feed"
status = 200
force = false 
