[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
  [[redirects]]
from = "/request-guest-article"
to = "/recognition"
status = 200
force = false 
