[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.40.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
  # Rewrite a path
/feed.xml /feed    200 
  
  
 

